import type { SxProps, Theme } from '@mui/material';

export const authScreenStyles: Record<string, SxProps<Theme>> = {
  gradientBg: {
    minHeight: '100vh',
    minWidth: '100vw',
    width: '100vw',
    height: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, #16a34a 0%, #2563eb 60%, #facc15 100%)',
    fontFamily: 'Inter, sans-serif',
    padding: { xs: '0.5rem', md: '1.5rem' },
    overflow: 'auto',
  },
  paper: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    borderRadius: 6,
    width: '100%',
    maxWidth: 900,
    minHeight: { xs: 500, md: 500 },
    boxShadow: 8,
    overflow: 'hidden',
    margin: 'auto',
  },
  brandCol: {
    background: 'linear-gradient(135deg, #16a34a 0%, #2563eb 60%, #facc15 100%)',
    color: '#fff',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    padding: { xs: '2rem 1rem 1.5rem 1rem', md: '3rem 2rem' },
    minWidth: 0,
    flex: { xs: 'unset', md: 0.4 },
    borderRadius: { xs: '1.5rem 1.5rem 0 0', md: '1.5rem 0 0 1.5rem' },
    borderTopRightRadius: { xs: 0, md: 0 },
    borderBottomRightRadius: { xs: 0, md: 0 },
  },
  formCol: {
    background: '#fff',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: { xs: '2rem 1rem 2rem 1rem', md: '3rem 2.5rem' },
    minWidth: 0,
    flex: { xs: 'unset', md: 0.6 },
    borderRadius: { xs: '0 0 1.5rem 1.5rem', md: '0 1.5rem 1.5rem 0' },
    borderTopLeftRadius: { xs: 0, md: 0 },
    borderBottomLeftRadius: { xs: 0, md: 0 },
  },
  logoCircle: {
    width: 180,
    height: 180,
    borderRadius: '50%',
    background: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 3,
    boxShadow: '0 4px 24px 0 rgba(0,0,0,0.10)',
    border: '6px solid #fff',
  },
  title: {
    fontWeight: 800,
    mb: 2,
    lineHeight: 1.1,
    textShadow: '0 2px 8px rgba(0,0,0,0.15)',
    fontSize: { xs: 28, md: 36 },
  },
  subtitle: {
    opacity: 0.95,
    textShadow: '0 1px 4px rgba(0,0,0,0.10)',
    fontSize: { xs: 15, md: 18 },
  },
  tabs: {
    mb: 5,
    '& .MuiTabs-indicator': { backgroundColor: '#16a34a', height: 5, borderRadius: 3 },
  },
};

export const tabStyle = (active: boolean): SxProps<Theme> => ({
  fontWeight: 700,
  fontSize: 20,
  color: active ? '#16a34a' : '#555',
  background: active ? '#e8f5e9' : '#f5f5f5',
  borderTopLeftRadius: 16,
  borderBottomLeftRadius: 16,
  minWidth: 140,
});

export const tabRightStyle = (active: boolean): SxProps<Theme> => ({
  fontWeight: 700,
  fontSize: 20,
  color: active ? '#16a34a' : '#555',
  background: active ? '#e8f5e9' : '#f5f5f5',
  borderTopRightRadius: 16,
  borderBottomRightRadius: 16,
  minWidth: 140,
});
